import { jsPDF } from "jspdf";
import { formatDate, formatKES } from "./utils";

interface InvoiceData {
  invoiceNumber: string;
  jobNumber: string;
  clientName: string;
  clientPhone: string;
  workerName: string;
  jobType: string;
  description?: string;
  location?: string;
  amount: number;
  items?: { description: string; amount: number }[];
  createdAt: Date;
  companyName: string;
  companyPhone: string;
  brandColor?: string;
  footerText?: string;
}

interface JobCardData {
  jobNumber: string;
  clientName: string;
  clientPhone: string;
  workerName: string;
  workerPhone?: string;
  jobType: string;
  description?: string;
  location?: string;
  priority: string;
  scheduledDate?: Date | null;
  assignedAt?: Date | null;
  arrivedAt?: Date | null;
  completedAt?: Date | null;
  verifiedAt?: Date | null;
  finalAmount?: number | null;
  invoiceNumber?: string;
  otpCode?: string;
  postponeHistory?: { date: Date; reason: string }[];
  companyName: string;
  companyPhone: string;
  brandColor?: string;
  footerText?: string;
}

function hexToRgb(hex: string | undefined): [number, number, number] {
  const fallback: [number, number, number] = [37, 99, 235];
  if (!hex) return fallback;
  const normalized = hex.replace("#", "").trim();
  if (!/^[0-9a-f]{6}$/i.test(normalized)) return fallback;
  return [
    parseInt(normalized.slice(0, 2), 16),
    parseInt(normalized.slice(2, 4), 16),
    parseInt(normalized.slice(4, 6), 16),
  ];
}

function header(doc: jsPDF, companyName: string, companyPhone: string, title: string, brandColor?: string) {
  const [r, g, b] = hexToRgb(brandColor);
  doc.setFillColor(r, g, b);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(companyName, 14, 12);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(companyPhone, 14, 20);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 196, 12, { align: "right" });
  doc.setTextColor(0, 0, 0);
}

function sectionTitle(doc: jsPDF, text: string, y: number, brandColor?: string): number {
  const [r, g, b] = hexToRgb(brandColor);
  doc.setFillColor(240, 245, 255);
  doc.rect(10, y, 190, 7, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(r, g, b);
  doc.text(text, 14, y + 5);
  doc.setTextColor(0, 0, 0);
  return y + 10;
}

function row(doc: jsPDF, label: string, value: string, y: number, x = 14): number {
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "bold");
  doc.text(label + ":", x, y);
  doc.setFont("helvetica", "normal");
  doc.text(value || "—", x + 45, y);
  return y + 6;
}

export function generateInvoicePDF(data: InvoiceData): Uint8Array {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  header(doc, data.companyName, data.companyPhone, "INVOICE", data.brandColor);

  let y = 36;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice #: ${data.invoiceNumber}`, 14, y);
  doc.text(`Date: ${formatDate(data.createdAt)}`, 140, y);
  y += 6;
  doc.text(`Job #: ${data.jobNumber}`, 14, y);
  y += 10;

  y = sectionTitle(doc, "BILLED TO", y, data.brandColor);
  y = row(doc, "Client", data.clientName, y);
  y = row(doc, "Phone", data.clientPhone, y);
  y += 4;

  y = sectionTitle(doc, "SERVICE DETAILS", y, data.brandColor);
  y = row(doc, "Service", data.jobType, y);
  if (data.description) y = row(doc, "Description", data.description, y);
  if (data.location) y = row(doc, "Location", data.location, y);
  y = row(doc, "Technician", data.workerName, y);
  y += 4;

  // Items table
  y = sectionTitle(doc, "AMOUNT", y, data.brandColor);
  doc.setFillColor(220, 230, 255);
  doc.rect(10, y, 190, 7, "F");
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "bold");
  doc.text("Description", 14, y + 5);
  doc.text("Amount", 186, y + 5, { align: "right" });
  y += 10;

  const items = data.items?.length
    ? data.items
    : [{ description: data.jobType, amount: data.amount }];

  for (const item of items) {
    doc.setFont("helvetica", "normal");
    doc.text(item.description, 14, y);
    doc.text(formatKES(item.amount), 196, y, { align: "right" });
    y += 6;
  }

  y += 2;
  const [r, g, b] = hexToRgb(data.brandColor);
  doc.setDrawColor(r, g, b);
  doc.line(10, y, 200, y);
  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("TOTAL", 14, y);
  doc.text(formatKES(data.amount), 196, y, { align: "right" });
  y += 12;

  // Footer note
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 100, 100);
  doc.text(data.footerText || "Thank you for your business. This invoice was auto-generated by FieldFlow.", 14, y);

  return doc.output("arraybuffer") as unknown as Uint8Array;
}

export function generateJobCardPDF(data: JobCardData): Uint8Array {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  header(doc, data.companyName, data.companyPhone, "JOB CARD", data.brandColor);

  let y = 36;
  doc.setFontSize(9);
  y = row(doc, "Job #", data.jobNumber, y);
  y = row(doc, "Priority", data.priority, y);
  y += 4;

  y = sectionTitle(doc, "CLIENT INFORMATION", y, data.brandColor);
  y = row(doc, "Name", data.clientName, y);
  y = row(doc, "Phone", data.clientPhone, y);
  if (data.location) y = row(doc, "Location", data.location, y);
  y += 4;

  y = sectionTitle(doc, "JOB DETAILS", y, data.brandColor);
  y = row(doc, "Type", data.jobType, y);
  if (data.description) y = row(doc, "Description", data.description, y);
  if (data.scheduledDate)
    y = row(doc, "Scheduled", formatDate(data.scheduledDate), y);
  y += 4;

  y = sectionTitle(doc, "ASSIGNED WORKER", y, data.brandColor);
  y = row(doc, "Name", data.workerName, y);
  if (data.workerPhone) y = row(doc, "Phone", data.workerPhone, y);
  y += 4;

  y = sectionTitle(doc, "TIMELINE", y, data.brandColor);
  if (data.assignedAt) y = row(doc, "Assigned", formatDate(data.assignedAt), y);
  if (data.arrivedAt) y = row(doc, "Arrived", formatDate(data.arrivedAt), y);
  if (data.completedAt) y = row(doc, "Completed", formatDate(data.completedAt), y);
  if (data.verifiedAt) y = row(doc, "Verified", formatDate(data.verifiedAt), y);
  y += 4;

  y = sectionTitle(doc, "FINANCIAL", y, data.brandColor);
  if (data.finalAmount) y = row(doc, "Amount", formatKES(data.finalAmount), y);
  if (data.invoiceNumber) y = row(doc, "Invoice #", data.invoiceNumber, y);
  y += 4;

  if (data.otpCode) {
    // OTP verification box — the digital signature
    doc.setFillColor(220, 255, 220);
    doc.rect(10, y, 190, 22, "F");
    doc.setDrawColor(0, 160, 0);
    doc.rect(10, y, 190, 22);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 120, 0);
    doc.text("✅  CLIENT VERIFICATION (Digital Signature)", 14, y + 7);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(`Service Code: ${data.otpCode}`, 14, y + 13);
    doc.text(
      `Verified at: ${data.verifiedAt ? formatDate(data.verifiedAt) : "—"}`,
      14,
      y + 19
    );
    y += 28;
  }

  if (data.postponeHistory?.length) {
    y = sectionTitle(doc, "POSTPONEMENT HISTORY", y, data.brandColor);
    for (const p of data.postponeHistory) {
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "normal");
      doc.text(`• ${formatDate(p.date)} — ${p.reason}`, 14, y);
      y += 6;
    }
  }

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(120, 120, 120);
  doc.text(
    "This document was auto-generated by FieldFlow. The Service Code above constitutes the client's digital signature.",
    14,
    285
  );

  return doc.output("arraybuffer") as unknown as Uint8Array;
}
